version: '2.1'
services:
  sdv-sqlite:
    image: timabell/sdv
    ports:
      - "80:8080"
  sdv-advwrks:
    image: timabell/sdv
    ports:
      - "8080:8080"
    environment:
      schemaexplorer_driver: mssql
      schemaexplorer_mssql_connection_string: "server=sdv-adventureworks.database.windows.net;user id=sdvRO;password=Startups 4 the rest of us;database=AdventureWorksLT"
  sdv-wwi:
    image: timabell/sdv
    ports:
      - "8081:8080"
    environment:
      schemaexplorer_driver: mssql
      schemaexplorer_mssql_connection_string: "server=sdv-wwi.database.windows.net;user id=sdvRO;password=Startups 4 the rest of us;database=WideWorldImporters"
